// <auto-generated />
using System;
using Golestan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Golestan.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250604221321_dsat")]
    partial class dsat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Golestan.Models.Classrooms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Room_Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("Golestan.Models.Courses", b =>
                {
                    b.Property<int>("Department_Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Final_Exam_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Section_Id")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Department_Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Golestan.Models.Departments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Golestan.Models.Instructors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Department_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Hire_Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Department_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("Golestan.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = 3
                        });
                });

            modelBuilder.Entity("Golestan.Models.Sections", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Classroom_Id")
                        .HasColumnType("int");

                    b.Property<int>("Course_Id")
                        .HasColumnType("int");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<int>("Time_Slot_Id")
                        .HasColumnType("int");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Classroom_Id");

                    b.HasIndex("Course_Id")
                        .IsUnique();

                    b.HasIndex("Time_Slot_Id");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("Golestan.Models.Students", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Depatment_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Enrollment_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Depatment_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Golestan.Models.Takes", b =>
                {
                    b.Property<int>("Student_Id")
                        .HasColumnType("int");

                    b.Property<int>("Section_Id")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.HasKey("Student_Id", "Section_Id");

                    b.HasIndex("Section_Id");

                    b.ToTable("Takes");
                });

            modelBuilder.Entity("Golestan.Models.Teaches", b =>
                {
                    b.Property<int>("Instructor_Id")
                        .HasColumnType("int");

                    b.Property<int>("Section_Id")
                        .HasColumnType("int");

                    b.HasKey("Instructor_Id", "Section_Id");

                    b.HasIndex("Section_Id");

                    b.ToTable("Teaches");
                });

            modelBuilder.Entity("Golestan.Models.Time_Slots", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End_Time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start_Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Time_Slots");
                });

            modelBuilder.Entity("Golestan.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hashed_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 10203040,
                            Created_at = new DateTime(2000, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "System@gmai",
                            First_name = "mananger",
                            Hashed_password = "1234",
                            Last_name = "system"
                        });
                });

            modelBuilder.Entity("User_Role", b =>
                {
                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.Property<int>("Role_Id")
                        .HasColumnType("int");

                    b.HasKey("User_Id", "Role_Id");

                    b.HasIndex("Role_Id");

                    b.ToTable("User_Roles");

                    b.HasData(
                        new
                        {
                            User_Id = 10203040,
                            Role_Id = 3
                        });
                });

            modelBuilder.Entity("Golestan.Models.Courses", b =>
                {
                    b.HasOne("Golestan.Models.Departments", "departments")
                        .WithMany("courses")
                        .HasForeignKey("Department_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("departments");
                });

            modelBuilder.Entity("Golestan.Models.Instructors", b =>
                {
                    b.HasOne("Golestan.Models.Departments", "departments")
                        .WithMany("instructors")
                        .HasForeignKey("Department_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Golestan.Models.Users", "User")
                        .WithMany("instructors")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("departments");
                });

            modelBuilder.Entity("Golestan.Models.Sections", b =>
                {
                    b.HasOne("Golestan.Models.Classrooms", "classrooms")
                        .WithMany("sections")
                        .HasForeignKey("Classroom_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Golestan.Models.Courses", "courses")
                        .WithOne("sections")
                        .HasForeignKey("Golestan.Models.Sections", "Course_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Golestan.Models.Time_Slots", "time_slots")
                        .WithMany("sections")
                        .HasForeignKey("Time_Slot_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("classrooms");

                    b.Navigation("courses");

                    b.Navigation("time_slots");
                });

            modelBuilder.Entity("Golestan.Models.Students", b =>
                {
                    b.HasOne("Golestan.Models.Departments", "departments")
                        .WithMany("students")
                        .HasForeignKey("Depatment_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Golestan.Models.Users", "User")
                        .WithMany("students")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("departments");
                });

            modelBuilder.Entity("Golestan.Models.Takes", b =>
                {
                    b.HasOne("Golestan.Models.Sections", "sections")
                        .WithMany("takes")
                        .HasForeignKey("Section_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Golestan.Models.Students", "students")
                        .WithMany("takes")
                        .HasForeignKey("Student_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("sections");

                    b.Navigation("students");
                });

            modelBuilder.Entity("Golestan.Models.Teaches", b =>
                {
                    b.HasOne("Golestan.Models.Instructors", "instructors")
                        .WithMany("teaches")
                        .HasForeignKey("Instructor_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Golestan.Models.Sections", "sections")
                        .WithMany("teaches")
                        .HasForeignKey("Section_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("instructors");

                    b.Navigation("sections");
                });

            modelBuilder.Entity("User_Role", b =>
                {
                    b.HasOne("Golestan.Models.Roles", "roles")
                        .WithMany("User_Roles")
                        .HasForeignKey("Role_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Golestan.Models.Users", "users")
                        .WithMany("User_Roles")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("roles");

                    b.Navigation("users");
                });

            modelBuilder.Entity("Golestan.Models.Classrooms", b =>
                {
                    b.Navigation("sections");
                });

            modelBuilder.Entity("Golestan.Models.Courses", b =>
                {
                    b.Navigation("sections")
                        .IsRequired();
                });

            modelBuilder.Entity("Golestan.Models.Departments", b =>
                {
                    b.Navigation("courses");

                    b.Navigation("instructors");

                    b.Navigation("students");
                });

            modelBuilder.Entity("Golestan.Models.Instructors", b =>
                {
                    b.Navigation("teaches");
                });

            modelBuilder.Entity("Golestan.Models.Roles", b =>
                {
                    b.Navigation("User_Roles");
                });

            modelBuilder.Entity("Golestan.Models.Sections", b =>
                {
                    b.Navigation("takes");

                    b.Navigation("teaches");
                });

            modelBuilder.Entity("Golestan.Models.Students", b =>
                {
                    b.Navigation("takes");
                });

            modelBuilder.Entity("Golestan.Models.Time_Slots", b =>
                {
                    b.Navigation("sections");
                });

            modelBuilder.Entity("Golestan.Models.Users", b =>
                {
                    b.Navigation("User_Roles");

                    b.Navigation("instructors");

                    b.Navigation("students");
                });
#pragma warning restore 612, 618
        }
    }
}
